name: "⚠️ Security Vulnerability"
description: Report a potential security issue privately if needed.
title: "⚠️ [SECURITY] - <short description>"
labels: ["security", "urgent"]
body:
  - type: textarea
    id: vulnerability-description
    attributes:
      label: "Description of the Vulnerability"
      description: Describe the vulnerability and why it is critical.
      placeholder: e.g. SQL Injection in the login endpoint
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: "Affected Components"
      description: Indicate which modules, endpoints, or libraries are impacted.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce (optional)"
      description: List actions to replicate the vulnerability.
      placeholder: |
        1. Go to '...'
        2. Send payload '...'
        3. See unauthorized access
      render: bash
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "Evidence (Screenshots, Payloads)"
      description: Include files or paste links after submission.
      placeholder: e.g. https://imgur.com/exploit.png or upload below
    validations:
      required: false

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "Checklist"
      options:
        - label: "I have used the search function to check if an issue already exists."
          required: true
